import Head from "next/head";
import Link from "next/link";
import { InitialsAvatar } from "@twa-dev/mark42";
import WebApp from "@twa-dev/sdk";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <InitialsAvatar
          entityId={12345}
          entityName="Artur Stambultsian"
          theme="apple"
          className="MyAvatar"
          style={{ marginRight: 10 }}
        />
        <button
          onClick={() =>
            WebApp.showAlert(`Hello World! Current count is ${count}`)
          }
        >
          Show Alert
        </button>
      </main>
    </>
  );
}
